name: CI - features branches

# Controls when the action will run. 
on:
  push:
    branches:
        - 'feature**'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge-develop-to-branch:
    name: Merge develop -> branch
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}

  tests:
    name: Correr pruebas
    runs-on: ubuntu-latest
    needs: merge-develop-to-branch
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests

  merge-branch-to-develop:
    name: Merge branch -> develop
    runs-on: ubuntu-latest
    needs: tests
    if: ${{contains(github.event.head_commit.message.message, 'merge_to_develop')}}
    steps:
      - name: automerge
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop